export const generatedPluginFiles = Object.freeze([
  Object.freeze({
    destination: "plugins/hope-commit/LICENSE",
    source: "LICENSE",
  }),
  Object.freeze({
    destination: "plugins/hope-commit/NOTICE",
    source: "NOTICE",
  }),
]);

export const staticPluginFiles = Object.freeze([
  "plugins/hope-commit/.claude-plugin/plugin.json",
  "plugins/hope-commit/.codex-plugin/plugin.json",
  "plugins/hope-commit/assets/hope-protected-light.png",
  "plugins/hope-commit/assets/hope-icon.png",
  "plugins/hope-commit/assets/fonts/HopeCode.woff2",
  "plugins/hope-commit/assets/fonts/HopeSansBold.woff2",
  "plugins/hope-commit/assets/fonts/HopeSansLight.woff2",
  "plugins/hope-commit/assets/fonts/HopeSansMedium.woff2",
  "plugins/hope-commit/assets/fonts/OFL-D2Coding.txt",
  "plugins/hope-commit/assets/fonts/OFL-Gmarket.txt",
  "plugins/hope-commit/assets/fonts/SOURCE.md",
  "plugins/hope-commit/skills/align/SKILL.md",
  "plugins/hope-commit/skills/align/agents/openai.yaml",
  "plugins/hope-commit/skills/align/references/artifact.md",
  "plugins/hope-commit/skills/align/references/design-directions.md",
  "plugins/hope-commit/skills/align/scripts/align-input-v2.schema.json",
  "plugins/hope-commit/skills/align/scripts/artifact.mjs",
  "plugins/hope-commit/skills/align/scripts/cli.mjs",
  "plugins/hope-commit/skills/align/scripts/design/tokens.mjs",
  "plugins/hope-commit/skills/align/scripts/render.mjs",
  "plugins/hope-commit/skills/diff/SKILL.md",
  "plugins/hope-commit/skills/diff/agents/openai.yaml",
  "plugins/hope-commit/skills/diff/assets/hope-protected-light.png",
  "plugins/hope-commit/skills/diff/references/analysis.md",
  "plugins/hope-commit/skills/diff/references/runtime.md",
  ...[
    "analysis-v3.schema.json",
    "artifact.mjs",
    "checkpoint-window-v2.schema.json",
    "checkpoint.mjs",
    "cli.mjs",
    "code-evidence.mjs",
    "command-options.mjs",
    "constants.mjs",
    "context.mjs",
    "derive.mjs",
    "evidence-range.mjs",
    "finalize.mjs",
    "github.mjs",
    "hash.mjs",
    "index.mjs",
    "redact.mjs",
    "render.mjs",
    "run.mjs",
    "structured-input.mjs",
    "target.mjs",
    "teaching-aids.mjs",
    "text.mjs",
    "validate.mjs",
  ].map((name) => `plugins/hope-commit/skills/diff/scripts/${name}`),
  "plugins/hope-commit/skills/diff/scripts/design/tokens.mjs",
  "plugins/hope-commit/skills/diff/scripts/locales/en-US/common.json",
  "plugins/hope-commit/skills/diff/scripts/locales/en-US/diff.json",
  "plugins/hope-commit/skills/diff/scripts/locales/index.mjs",
  "plugins/hope-commit/skills/diff/scripts/locales/ko-KR/common.json",
  "plugins/hope-commit/skills/diff/scripts/locales/ko-KR/diff.json",
  "plugins/hope-commit/skills/commit-diff/SKILL.md",
  "plugins/hope-commit/skills/commit-diff/agents/openai.yaml",
  "plugins/hope-commit/skills/commit-diff/assets/hope-protected-light.png",
  "plugins/hope-commit/skills/commit-diff/references/analysis.md",
  "plugins/hope-commit/skills/commit-diff/references/runtime.md",
  ...[
    "analysis-v3.schema.json",
    "artifact.mjs",
    "checkpoint-window-v2.schema.json",
    "checkpoint.mjs",
    "cli.mjs",
    "code-evidence.mjs",
    "command-options.mjs",
    "constants.mjs",
    "derive.mjs",
    "evidence-range.mjs",
    "finalize.mjs",
    "git-context.mjs",
    "git.mjs",
    "hash.mjs",
    "index.mjs",
    "redact.mjs",
    "render.mjs",
    "run.mjs",
    "structured-input.mjs",
    "target.mjs",
    "teaching-aids.mjs",
    "text.mjs",
    "validate.mjs",
  ].map((name) => `plugins/hope-commit/skills/commit-diff/scripts/${name}`),
  "plugins/hope-commit/skills/commit-diff/scripts/design/tokens.mjs",
  "plugins/hope-commit/skills/commit-diff/scripts/locales/en-US/common.json",
  "plugins/hope-commit/skills/commit-diff/scripts/locales/en-US/diff.json",
  "plugins/hope-commit/skills/commit-diff/scripts/locales/index.mjs",
  "plugins/hope-commit/skills/commit-diff/scripts/locales/ko-KR/common.json",
  "plugins/hope-commit/skills/commit-diff/scripts/locales/ko-KR/diff.json",
  "plugins/hope-commit/skills/polish/SKILL.md",
  "plugins/hope-commit/skills/polish/agents/openai.yaml",
  "plugins/hope-commit/skills/polish/references/code.md",
  "plugins/hope-commit/skills/sweep/SKILL.md",
  "plugins/hope-commit/skills/sweep/agents/openai.yaml",
  "plugins/hope-commit/skills/toxic-review/SKILL.md",
  "plugins/hope-commit/skills/toxic-review/agents/openai.yaml",
  "plugins/hope-commit/skills/toxic-review/references/causal-review.md",
  "plugins/hope-commit/skills/write/SKILL.md",
  "plugins/hope-commit/skills/write/agents/openai.yaml",
  "plugins/hope-commit/skills/write/assets/hope-protected-light.png",
  "plugins/hope-commit/skills/write/references/writing-standard.md",
]);

export const pluginPackageFiles = Object.freeze([
  ...generatedPluginFiles.map((entry) => entry.destination),
  ...staticPluginFiles,
].map((path) => path.replace(/^plugins\/hope-commit\//u, "")).sort());
